name: check edited

description: Check target file(s) is updated between given branches

inputs:
  source-remote:
    description: 'source remote repository'
    default: 'origin'

  source-branch:
    description: 'source branch'
    default: 'HEAD'

  target-remote:
    description: 'target remote repository'
    default: 'origin'

  target-branch:
    description: 'target branch'
    default: 'main'
    required: true

  target-file:
    description: 'file(s) you want to check (comma separated)'
    required: true

runs:
  using: composite
  steps:
    - run: |
        set -euo pipefail

        source_refs="refs/remotes/$SOURCE_REMOTE/$SOURCE_BRANCH"
        target_refs="refs/remotes/$TARGET_REMOTE/$TARGET_BRANCH"

        echo "Using $source_refs for source"
        git fetch --depth=1 --quiet "$SOURCE_REMOTE" "$SOURCE_BRANCH"

        echo "Using $target_refs for target"
        git fetch --depth=1 --quiet "$TARGET_REMOTE" "$TARGET_BRANCH"

        echo
        echo "================================================"
        echo "| source-refs: $source_refs                     "
        echo "| target-refs: $target_refs                     "
        echo "| target-file: $TARGET_FILE                     "
        echo "================================================"
        echo

        echo "$TARGET_FILE" | tr ',' '\n' | while read -r file; do
          file=$(printf '%q' "$file")
          git_diff_ret_code=0
          git diff --exit-code "$target_refs..$source_refs" -- "$file" || git_diff_ret_code=$?
          if [ $git_diff_ret_code != 1 ]; then
            echo "$file is not updated."
            exit 1
          fi
        done
      shell: bash
      env:
        SOURCE_REMOTE: "${{ inputs.source-remote }}"
        SOURCE_BRANCH: "${{ inputs.source-branch }}"
        TARGET_REMOTE: "${{ inputs.target-remote }}"
        TARGET_BRANCH: "${{ inputs.target-branch }}"
        TARGET_FILE: "${{ inputs.target-file }}"
