name: test with skip

on: pull_request

jobs:
  main:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-check') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: himkt/check-edited@main
        with:
          target-file: LICENSE
